title: Nanum Jeon
description: Ph.D. Candidate in Sociology at UCLA
url: "https://nanum-jeon.github.io"
baseurl: ""
markdown: kramdown

plugins:
  - jekyll-seo-tag

exclude:
  - README.md
  - LICENSE
